name: "Run tests"
description: "Runs the tests"
runs:
  using: "composite"
  steps:
    - name: Install deps
      run: npm install
      shell: bash

    - name: Test
      run: npm run test
      shell: bash