name: "Run tests"
description: "Runs the tests. Requires that the repo is checked out and gcloud credentials are set."
runs:
  using: "composite"
  steps:
    - name: Install deps
      run: npm ci
      shell: bash

    - name: Test
      run: npm run test
      shell: bash